# Generated by Django 5.2.7 on 2025-10-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=6)),
                ('descricao', models.CharField(max_length=200)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_cadastro', models.CharField(max_length=20)),
            ],
        ),
    ]
