# Generated by Django 5.2.7 on 2025-10-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=11)),
                ('cliente', models.CharField(max_length=20)),
                ('produto', models.CharField(max_length=50)),
                ('quantidade', models.CharField(max_length=50)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('endereco', models.CharField(max_length=20)),
            ],
        ),
    ]
