# Generated by Django 5.2.7 on 2025-10-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.CharField(default='19/10/2025', max_length=20),
            preserve_default=False,
        ),
    ]
