# Generated by Django 5.2.7 on 2025-10-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=20)),
                ('logradouro', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=14)),
                ('padrao', models.BooleanField()),
            ],
        ),
    ]
